all:
	pdflatex PhysAPC-EM-C03-notice
	pdflatex PhysAPC-EM-C03-notice
#	cd homework ; make

clean:
	rm -rf *~ *.*~ *.log *.nav *.aux *.out *.snm *.toc

public:
	mkdir -p $(DESTINATION)/Class03
	cp *.pdf $(DESTINATION)/Class03
#	cp homework/*-Homework.pdf $(DESTINATION)/Class03
