all:
	xelatex PhysAPC-01-courseOutline
	xelatex PhysAPC-01-courseOutline

clean:
	rm -rf *~ *.*~ *.log *.nav *.aux *.out *.snm *.toc

public:
	mkdir -p $(DESTINATION)/Class01
	cp *.pdf $(DESTINATION)/Class01

