all:
	xelatex PhysAPC-04-MomentumImpulse;
	xelatex PhysAPC-04-MomentumImpulse;

clean:
	rm -rf *~ *.*~ *.log *.nav *.aux *.out *.snm *.toc

public:
	mkdir -p $(DESTINATION)/Topic04
	cp *.pdf $(DESTINATION)/Topic04
