all:
	xelatex PhysAPC-15-gaussLaw
	xelatex PhysAPC-15-gaussLaw

clean:
	rm -rf *~ *.*~ *.log *.nav *.aux *.out *.snm *.toc

public:
	mkdir -p $(DESTINATION)/Class15
	cp PhysAPC*.pdf $(DESTINATION)/Class15
