all:
	xelatex PhysAPC-01a-vectorsCalculus
	xelatex PhysAPC-01a-vectorsCalculus
	xelatex PhysAPC-01b-kinematicsHandout
	xelatex PhysAPC-01b-kinematicsHandout
	xelatex PhysAPC-01c-motionGraphs
	xelatex PhysAPC-01c-motionGraphs
	xelatex PhysAPC-01d-projectileMotion
	xelatex PhysAPC-01d-projectileMotion


clean:
	rm -rf *.aux *.log *.out *.*~ *~
