all:
	xelatex PhysAPC-22b-MaxwellEqs
	xelatex PhysAPC-22b-MaxwellEqs

clean:
	rm -rf *~ *.*~ *.log *.nav *.aux *.out *.snm *.toc

public:
	mkdir -p $(DESTINATION)/Class22
	cp *.pdf $(DESTINATION)/Class22
