all:
	pdflatex PhysAPC-Mech-C12-harmonicMotion
	pdflatex PhysAPC-Mech-C12-harmonicMotion
	pdflatex PhysAPC-Mech-C12-harmonicMotion-print
	pdflatex PhysAPC-Mech-C12-harmonicMotion-print
clean:
	rm -rf *~ *.*~ *.log *.nav *.aux *.out *.snm *.toc


public:
	mkdir -p $(DESTINATION)/Class12
	cp *.pdf $(DESTINATION)/Class12
