all:
	pdflatex PhysAPC-EM-C14b-maxwellEqs
	pdflatex PhysAPC-EM-C14b-maxwellEqs

clean:
	rm -rf *~ *.*~ *.log *.nav *.aux *.out *.snm *.toc

public:
	mkdir -p $(DESTINATION)/Class14
	cp *.pdf $(DESTINATION)/Class14
