all:
	pdflatex PhysAPC-EM-C08-practiceTest1-MCQ
	pdflatex PhysAPC-EM-C08-practiceTest1-MCQ
	pdflatex PhysAPC-EM-C16-practiceTest2-FRQ
	pdflatex PhysAPC-EM-C16-practiceTest2-FRQ

clean:
	rm -rf *~ *.*~ *.log *.nav *.aux *.out *.snm *.toc

public:
	mkdir -p $(DESTINATION)/Class16
	cp *.pdf $(DESTINATION)/Class16
