all:
	pdflatex PhysAPC-Mech-C02a-graphingTechniques
	pdflatex PhysAPC-Mech-C02a-graphingTechniques
	pdflatex PhysAPC-Mech-C02a-graphingTechniques-print
	pdflatex PhysAPC-Mech-C02a-graphingTechniques-print

clean:
	rm -rf *~ *.*~ *.log *.nav *.aux *.out *.snm *.toc

public:
	mkdir -p $(DESTINATION)/Class02
	cp *.pdf $(DESTINATION)/Class02
