all:
	pdflatex PhysAPC-Mech-C02a-kinematics2
	pdflatex PhysAPC-Mech-C02a-kinematics2
	pdflatex PhysAPC-Mech-C02a-kinematics2-print
	pdflatex PhysAPC-Mech-C02a-kinematics2-print

clean:
	rm -rf *~ *.*~ *.log *.nav *.aux *.out *.snm *.toc

public:
	mkdir -p $(DESTINATION)/Class02
	cp *.pdf $(DESTINATION)/Class02
