all:
	pdflatex PhysAPC-EM-C07-homework
	pdflatex PhysAPC-EM-C07-homework

clean:
	rm -rf *~ *.*~ *.log *.nav *.aux *.out *.snm *.toc

public:
	mkdir -p $(DESTINATION)/Class07
	cp *.pdf $(DESTINATION)/Class07
