all:
	pdflatex PhysAPC-EM-C07-notice
	pdflatex PhysAPC-EM-C07-notice

clean:
	rm -rf *~ *.*~ *.log *.nav *.aux *.out *.snm *.toc

public:
	mkdir -p $(DESTINATION)/Class07
	cp *.pdf $(DESTINATION)/Class07
