all:
	xelatex PhysAPC-11-Electrostatics
	xelatex PhysAPC-11-Electrostatics

clean:
	rm -rf *~ *.*~ *.log *.nav *.aux *.out *.snm *.toc

public:
	mkdir -p $(DESTINATION)/Topic11
	cp *.pdf $(DESTINATION)/Topic11
