all:
	xelatex PhysAP2-12-Capacitors
	xelatex PhysAP2-12-Capacitors

clean:
	rm -rf *~ *.*~ *.log *.nav *.aux *.out *.snm *.toc

public:
	mkdir -p $(DESTINATION)/Topic12
	cp *.pdf $(DESTINATION)/Topic12
