all:
	pdflatex PhysAPC-Mech-C03-multiBodyDynamics
	pdflatex PhysAPC-Mech-C03-multiBodyDynamics
#	cd homework ; make

clean:
	rm -rf *~ *.*~ *.log *.nav *.aux *.out *.snm *.toc
#	cd homework ; make clean

public:
	mkdir -p $(DESTINATION)/Class03
	cp *.pdf $(DESTINATION)/Class03
#	cp homework/*-Homework.pdf $(DESTINATION)/Class03
