all:
	pdflatex PhysAPC-Mech-C16-Test2
	pdflatex PhysAPC-Mech-C16-Test2
	pdflatex PhysAPC-Mech-C16-Test2-FRQ
	pdflatex PhysAPC-Mech-C16-Test2-FRQ

clean:
	rm -rf *~ *.*~ *.log *.nav *.aux *.out *.snm *.toc

public:
	mkdir -p $(DESTINATION)/Class16
	cp *-notice.pdf $(DESTINATION)/Class16
