all:
	pdflatex PhysAPC-Mech-12-harmonicMotion
	pdflatex PhysAPC-Mech-12-harmonicMotion
	pdflatex PhysAPC-Mech-12-harmonicMotion-print
	pdflatex PhysAPC-Mech-12-harmonicMotion-print
#	cd homework ; make
clean:
	rm -rf *~ *.*~ *.log *.nav *.aux *.out *.snm *.toc
#	cd homework ; make clean

public:
	mkdir -p $(DESTINATION)/Class12
	cp *.pdf $(DESTINATION)/Class12
#	cp homework/*Homework.pdf $(DESTINATION)/Class10
