all:
	xelatex PhysAPC-12-Electrostatics
	xelatex PhysAPC-12-Electrostatics

clean:
	rm -rf *~ *.*~ *.log *.nav *.aux *.out *.snm *.toc

public:
	mkdir -p $(DESTINATION)/Class12
	cp *.pdf $(DESTINATION)/Class12
