all:
	pdflatex PhysAPC-Mech-C05-momentum
	pdflatex PhysAPC-Mech-C05-momentum
	pdflatex PhysAPC-Mech-C05-momentum-print
	pdflatex PhysAPC-Mech-C05-momentum-print

clean:
	rm -rf *~ *.*~ *.log *.nav *.aux *.out *.snm *.toc

public:
	mkdir -p $(DESTINATION)/Class05
	cp *.pdf $(DESTINATION)/Class05
