TERM=Current-Physics-Curriculum-Courses
CLOUD=ossfiles
WORK_DIR=000-Timothy\ L
DESTINATION=$(HOME)/Documents/$(CLOUD)/$(WORK_DIR)/$(TERM)/Physics.APC-EM
#DESTINATION=$(HOME)/Documents/$(CLOUD)/$(TERM)/Physics.APC-EM

export 

all:
	cd Class01-electrostatics ; make
	cd Class02-electrostatics-part2 ; make
#	cd Class03b-workEnergy ; make
#	cd Class04-workEnergy-part2 ; make
#	cd Class05-momentumImpulse ; make
#	cd Class06-CM		; make
#	cd Class07-circMotion	; make
#	cd Class09-rotMotion-part1	; make
#	cd Class10-rotMotion-part2	; make
#	cd Class11-rotMotion-part3	; make
#	cd Class12-harmonicMotion-part1 ; make
#	cd Class13-harmonicMotion-part2 ; make
#	cd Class14-universalGravitation ; make
#	cd Class15-planetaryMotion	; make

clean:
	rm -rf *.*~ *~ *.log
	cd Class01-electrostatics ; make clean
	cd Class02-electrostatics-part2 ; make clean
#	cd Class03a-multiBodyDynamics ; make clean
#	cd Class03b-workEnergy	; make clean
#	cd Class04-workEnergy-part2 ; make clean
#	cd Class05-momentumImpulse ; make clean
#	cd Class06-CM		; make clean
#	cd Class07-circMotion	; make clean
#	cd Class09-rotMotion-part1	; make clean
#	cd Class10-rotMotion-part2	; make clean
#	cd Class11-rotMotion-part3	; make clean
#	cd Class12-harmonicMotion-part1 ; make clean
#	cd Class13-harmonicMotion-part2 ; make clean
#	cd Class14-universalGravitation ; make clean
#	cd Class15-planetaryMotion	; make clean

public:
	mkdir -p $(DESTINATION)
	cd Class01-electrostatics ; make public
	cd Class02-electrostatics-part2 ; make public
#	cd Class03a-multiBodyDynamics ; make public
#	cd Class03b-workEnergy	; make public
#	cd Class04-workEnergy-part2 ; make public
#	cd Class05-momentumImpulse ; make public
#	cd Class06-CM		; make public
#	cd Class07-circMotion	; make public
#	cd Class09-rotMotion-part1	; make public
#	cd Class10-rotMotion-part2	; make public
#	cd Class11-rotMotion-part3	; make public
#	cd Class12-harmonicMotion-part1 ; make public
#	cd Class13-harmonicMotion-part2 ; make public
#	cd Class14-universalGravitation ; make public
#	cd Class15-planetaryMotion	; make public
