all:
	xelatex PhysAPC-10-mockTest-Classkick
	xelatex PhysAPC-10-mockTest-Classkick

clean:
	rm -rf *~ *.*~ *.log *.nav *.aux *.out *.snm *.toc

public:
	mkdir -p $(DESTINATION)/Topic10
	cp *-notice.pdf $(DESTINATION)/Topic10
