all:
	xelatex PhysAPC-19B-MaxwellEqs
	xelatex PhysAPC-19B-MaxwellEqs

clean:
	rm -rf *~ *.*~ *.log *.nav *.aux *.out *.snm *.toc

public:
	mkdir -p $(DESTINATION)/Class19
	cp *.pdf $(DESTINATION)/Class19
