all:
	xelatex PhysAPC-15-MaxwellEqs
	xelatex PhysAPC-15-MaxwellEqs

clean:
	rm -rf *~ *.*~ *.log *.nav *.aux *.out *.snm *.toc

public:
	mkdir -p $(DESTINATION)/Topic15
	cp *.pdf $(DESTINATION)/Topic15
