all:
	pdflatex PhysAPC-EM-C08-practiceTest1-MCQ
	pdflatex PhysAPC-EM-C08-practiceTest1-MCQ
	pdflatex PhysAPC-EM-C08-practiceTest1-FRQ
	pdflatex PhysAPC-EM-C08-practiceTest1-FRQ

clean:
	rm -rf *~ *.*~ *.log *.nav *.aux *.out *.snm *.toc

public:
	mkdir -p $(DESTINATION)/Class07
	cp *.pdf $(DESTINATION)/Class07
